# Generated by Django 4.2.3 on 2023-07-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminuser",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
    ]
