# Generated by Django 4.2.3 on 2023-07-20 05:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_adminuser_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminuser",
            name="is_staff",
        ),
    ]
