# Generated by Django 4.2.3 on 2023-07-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_adminuser_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminuser",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
    ]
