# Generated by Django 4.2.3 on 2023-07-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_post_episode_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={},
        ),
        migrations.AlterField(
            model_name="post",
            name="episode_number",
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
    ]
