# Generated by Django 4.2.3 on 2023-07-21 05:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_post_options_alter_post_episode_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["episode_number"]},
        ),
    ]
